Repository nasa/PSP, pull requests merged in 2021-02, with the labels that each got.

#245 Fix #230, Add workflow timeout and format check
  .github/workflows/format-check.yml
  .github/workflows/static-analysis.yml
  .travis.yml
  README.md
Labels: CCB:FastTrack, IC:2021-02-02, continuous-integration

#249 Fix #248, Add CodeQL analysis to workflow
  .github/workflows/codeql-build.yml
Labels: CCB:FastTrack, continuous-integration

#242 Fix #241, Add missing +dev to development version string
  fsw/inc/cfe_psp.h
  fsw/inc/cfe_psp_configdata.h
  fsw/mcp750-vxworks/inc/psp_version.h
  fsw/pc-linux/inc/psp_version.h
  fsw/pc-rtems/inc/psp_version.h
  fsw/shared/src/cfe_psp_configdata.c
Labels: CCB:2021-02-02, IC:2021-02-02
